### ISSUE TITLE
Redirected to a broken HTTPS page when using public domain

### ISSUE THREAD

**Issue by Orangian** [Forceu/Gokapi#10]
Hi. I just ran gokapi on a Debian 10 box with apache already installed and it works fine when using the internal IP address to connect, however, when I use my domain to try and connect to it, it changes my connection from being an HTTP connection to an HTTPS connection and FireFox throws the error: `SSL_ERROR_RX_RECORD_TOO_LONG`
I'm not sure whats wrong here, as it runs perfectly fine when using my internal IP, however, this defeats the purpose of using it to share files with others. All of the settings are default except it is not bound only to localhost and I'm not using a reverse proxy. Port 53842 is port forwarded.

**Comment by Forceu** [comment]
Are you using Cloudflare or have you set your up a redirection to HTTPS with your domain provider? It seems that something from that side is forcing HTTPS, which does not work if you are only redirecting the port, as the server provides only a HTTP connection.

I would strongly recommend using a reverse proxy (eg. nginx), so that a SSL certificate can be used or otherwise try to find the option where you can disable the HTTPS redirection for the domain and turn it off.

**Comment by Orangian** [comment]
Not using Cloudflare, and other HTTP only services work just fine. It may be conflicting with another piece of software on my server so I'll make a container on my Proxmox server with Gokapi on it and test it there.

**Comment by Orangian** [comment]
The latest build (v1.1.3) doesn't have a build yet and using go build on a fresh Debian 10 install (with golang installed) throws the error "build Gokapi: cannot find module for path embed" I'm probably doing something wrong but I'm going to use a build of 1.1.2 for now in my testing.

**Comment by Orangian** [comment]
I got it working on my original machine by typing exactly this "http://$WEBSITE.netgear.com/" Before I only typed "$WEBSITE.netgear.com" and adding the "http" before hand and a slash after fixed it. I guess that's a bug, but it sure is an odd one.

**Comment by Forceu** [comment]
Ah thanks, I forgot to add the binaries to the build!

> throws the error "build Gokapi: cannot find module for path embed"

You are probably using a Go version <1.16, as embed was added in 1.16 - you can try with the updated binary however. 

Hm I think it is rather a behaviour of Firefox in that case, the server itself should not redirect to HTTPS itself. As long as you copy the link with HTTP it should work however. Just note that all traffic will obviously be not encrypted, including passwords.

**Comment by Orangian** [comment]
Welp, it just went down again after I upgraded it. Not sure what happened there, I'm going to try and downgrade. I am copying the link with HTTP and I have tried Chromium instead of Firefox, same error.

**Comment by Orangian** [comment]
Who
