### ISSUE TITLE
Bug: Background could not be loaded

### ISSUE THREAD

**Issue by Jisagi** [Forceu/Gokapi#101]
The latest-dev docker container fails to load the background.jpg and just throws a 404. The url it tries to load it form is `https:/domain.tld/css/assets/background.jpg`. I wasn't able to find a reason why any of the recent commit breaks loading it. Is it only me encountering this problem?

EDIT:
I testing some more docker tags:
v1.6.2: works as before
v1.7.0: broken
latest: broken
latest-dev: broken

The last three are identical anyway, but still worth checking if its a random hickup with one of them.

**Comment by Forceu** [comment]
Thanks a lot for the bug report! It has been fixed in 9a91349 and I will release a new update containing the fix
