### ISSUE TITLE
Feature request: Edit items after upload (attributes, not files)

### ISSUE THREAD

**Issue by ehawman** [Forceu/Gokapi#103]
The #1 reason for re-upload is that I stupidly did/didn't check the Password box, or I mistyped the password, or the same but for limits/expiry.

Would it be possible to add an `Edit` button to the Actions, which would allow us to reset things like dl limits, expiry, password, etc. It would essentially be a reupload but using the same ID/file.

**Comment by Forceu** [comment]
Thanks for the feedback! That does indeed sound like a good idea. In the meantime, you can use the `duplicate` API call in case you uploaded a larger file

**Comment by ehawman** [comment]
Nice! I'll use this in the future. Thank you!

**Comment by Forceu** [comment]
Added in a130357
