### ISSUE TITLE
Bug: Error reading meta.json

### ISSUE THREAD

**Issue by bartzz** [Forceu/Gokapi#105]
Hello! I have the error below appear periodically, in most cases it comes up when files are being uploaded.

The Docker container (v1.7.2) dies and output is:
`error reading meta.json: unexpected end of JSON input`

Since I like gokapi and have some files (>500) I wrote a simple script to restart the container when that error occurs. 
Do you have any suspicions what might be causing it? Multithreaded write / race conditions that occur on the `meta.json` file? Maybe the file handle needs an `sync.RWMutex` ?

```bash
#!/bin/bash

URL="https://cdn.hidden.de/admin"
FILE_PATH="/srv/gokapi/data/filestorage.db/meta.json"
DOCKER_DIR="/srv/gokapi"

response=$(curl -sL -w "%{http_code}" "$URL" -o /dev/null)

if [[ "$response" -eq 200 ]]; then
  echo "URL is accessible. Exiting script."
  exit 0
else
  echo "URL is not accessible. Deleting file: $FILE_PATH"
  rm "$FILE_PATH"
fi

cd "$DOCKER_DIR" || exit 1

/usr/bin/docker compose up -d
```

Thank you!

**Comment by juampii** [comment]
Good days, thats happening to me also, very frecuent. Thanks you for this "solution"
Have a nice day

**Comment by bartzz** [comment]
@Forceu Great work! I didn't expect you to rewrite the whole persistence layer to another store. Thank you.
