### ISSUE TITLE
Unable to build/run tests

### ISSUE THREAD

**Issue by Kwonunn** [Forceu/Gokapi#109]
While developing I'm running into an issue with the tests. Running the test command I get the following output: 

```
$ go test internal/configuration/database/Database_test.go 
# command-line-arguments
package command-line-arguments (test)
        imports github.com/forceu/gokapi/internal/test: build constraints exclude all Go files in D:\Code\Gokapi\internal\test
FAIL    command-line-arguments [setup failed]
FAIL
```

I'm not very experienced with Go so I don't know what these build constraints are or where I can modify them. I am working on Windows.

**Comment by Forceu** [comment]
You will need the test constraint, e.g. to test all modules, execute the following in the root dir:

`go test ./... -parallel 8 --tags=test,awsmock`

Under Windows you might need to replace the `./...` with `.\...`

**Comment by Kwonunn** [comment]
After fiddling with some other IDE settings, this works. Thanks!
