### ISSUE TITLE
Feature request: silent drop alternative to redirect url and configurable admin path

### ISSUE THREAD

**Issue by d03j** [Forceu/Gokapi#117]
Hi there, 

Thank you for the great software.

Would it be possible to have an option to silently drop requests instead of redirecting them somewhere and make the admin path configurable as a little extra security?

**Comment by Forceu** [comment]
Hi, thanks for the feedback. What exactly do you mean with "dropping requestes"? Rejecting all packages? That would only be possible with modifing the webserver package, which is out of scope for this project. And even then I am not really sure if it is really feasable, as the client needs to establish a connection first and then requests the URL.
