### ISSUE TITLE
Bug: OAuth integration only works for providers that implement the "select_account" prompt

### ISSUE THREAD

**Issue by benjohns1** [Forceu/Gokapi#121]
Attempting to login with OIDC through Authelia (for instance) results in the error "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Used unknown value '[select_account]' for prompt parameter"

I think we could set a default value of "select_account" to work with Google by default so as not to break existing configs, but also allow overriding the prompt param in the config file so OIDC can be used with more providers.

**Comment by Forceu** [comment]
Thanks for the feedback, I just finished setting up oath2 for my Authelia instance a couple days ago, I will look into the issue this week

**Comment by benjohns1** [comment]
Great little project by the way. And nice response time :-) I just made a PR that should fix the issue while I *think* being backwards compatible, but I was having trouble getting the tests running locally.

**Comment by Forceu** [comment]
Fixed in fa4c0bc
