### ISSUE TITLE
Enhancement Request: Allow files to be replaced

### ISSUE THREAD

**Issue by beastarman74** [Forceu/Gokapi#128]
Allow files uploaded to Gokapi to be replaced with an updated version without changing the current created link. 

This would improve ease of use. As documents, images that are being collaborated on can be updated and a new link doesn't need to be sent for further access to continue. 

This could be an option to enable/disable the ability to do this if there is a concern that the file could be replaced mischievously.

**Comment by Forceu** [comment]
That sounds like a good idea, thanks for the feedback

**Comment by royaldunlin** [comment]
I support this. I was wanting to use the API to replace an existing file upon update but without this feature that isn't currently possible.

**Comment by Forceu** [comment]
Added in c167e75
