### ISSUE TITLE
Enhancement: Unlimited Downloads/Expiry

### ISSUE THREAD

**Issue by Jisagi** [Forceu/Gokapi#13]
Would it be possible to set maybe 0 as either/both download limit / expiry date, or would that break the idea of the project too much? Not knowing the possible downloads would be possible use case. As alternative to no expiry date, a datepicker like selection for expiry date would be a neat idea as well.

On another note, is it intended, that a changed download/expiry will also be written to the config?

**Comment by Forceu** [comment]
Thanks, I will put that on my todo list.

> is it intended, that a changed download/expiry will also be written to the config?

Yes, it is indeed intended. If you change the values in the main menu for new files, they do not revert back to the old value and become the new default. Changing this value will however not affect any already existing files.

**Comment by Forceu** [comment]
Added in f42faf8f53895632729ece3643eeced15a72fb8f
