### ISSUE TITLE
Feature Request: Environment variables for defaults

### ISSUE THREAD

**Issue by adammckay** [Forceu/Gokapi#131]
This is the best application for single file upload that I have used to this point.  It is nearly perfect for my use case! I hope that if you fulfill the feature request for user uploads that it is something that is off by default.

At any rate, I would like to be able to configure the default values of the 3 options on the main page: download limit, expiry, and password.  It would be nice to have 6 environment variables:

limit_checked: true/false
limit_value: integer
expiry_checked: true/false
expiry_value: integer
password_checked: true/false
password_value: string

I find that when I quickly drag and drop files, I have to set those values every time.  Defaults decided by the admin would be nice.
Thanks and keep up the great work!

**Comment by Forceu** [comment]
Hi, once you change the values and upload a file, these values would be the new defaults. Does this not happen?

**Comment by adammckay** [comment]
Omg...  it does!  Sry to bother....  great work on your part.

**Comment by Forceu** [comment]
No problem, good to hear that it's working :)

**Comment by MalteMagnussen** [comment]
> Hi, once you change the values and upload a file, these values would be the new defaults. Does this not happen?

Nice! It does indeed work @Forceu 

But it doesn't persist across restarts, sadly. 

Could this be re-opened with "very low prio"? :) 

Not important, but would be "nice to have". 

Realistically it would only save the users 1-2 clicks per person every time the Deployment is restarted.
