### ISSUE TITLE
SSL Self Signed Cert Lets Encrypt

### ISSUE THREAD

**Issue by xsasx** [Forceu/Gokapi#132]
Hi , have isntalled gokapi under a docker container behind an nginx reverse proxy and have a self signed lets encrypt certi. sadly i have only pem files - how can i use them under the gokapi docker as certifikate ?

**Comment by Forceu** [comment]
You can probably convert the pem file with this command:

`openssl x509 -outform der -in your-cert.pem -out your-cert.crt`

If you are using a reverse proxy anyways and do not expose the docker port, you most likely will not need SSL on Gokapi however, you can simply use the reverse proxy for SSL.
