### ISSUE TITLE
Create API key option to REST API

### ISSUE THREAD

**Issue by vectorkovacspeter** [Forceu/Gokapi#133]
Hello,

it would be nice, it there is a possibility to add new API keys.

The permission handling is already there (manage API key permission), so its together with the already exist /auth/friendlyname and /auth/modify endpoints gives the ability for us to automate or integrate this step.

**Comment by Forceu** [comment]
I was considering it before, but did not see a use case for it. I will probably add it with the next version though.

**Comment by Forceu** [comment]
Added in 9641e28
