### ISSUE TITLE
Enhancement: Add AWS S3 support

### ISSUE THREAD

**Issue by ahrenstein** [Forceu/Gokapi#14]
It would be really helpful if AWS S3 could be used as the storage backend for this.

**Comment by Forceu** [comment]
Thanks for the idea! Personally I haven't used AWS S3 before, but it seems straight forward to implement.

**Comment by ahrenstein** [comment]
Awesome! I was using https://github.com/timvisee/send but even with basic auth at the nginx level unauthorized users were finding ways to upload. Would love to switch to Gokapi if AWS S3 support was added. (Not much local storage on the server)

**Comment by Forceu** [comment]
I added S3 support, to test it, please use the `latest-dev` Docker image or the attached binaries. I would love to hear your feedback!

To use S3, you need to pass the following environment variables:

| Env | Description | Example |
| --- | --- | --- |
| GOKAPI_AWS_BUCKET | Bucket name | gokapi |
| AWS_REGION | Bucket region | eu-central-1 |
| AWS_ACCESS_KEY_ID | Access Key ID | awsaccesskey |
| AWS_SECRET_ACCESS_KEY | Access Key ID | secretkey |

[gokapi_full-darwin_amd64.zip](https://github.com/Forceu/Gokapi/files/6452074/gokapi_full-darwin_amd64.zip)
[gokapi_full-linux_amd64.zip](https://github.com/Forceu/Gokapi/files/6452075/gokapi_full-linux_amd64.zip)
[gokapi_full-windows_amd64.exe.zip](https://github.com/Forceu/Gokapi/files/6452076/gokapi_full-windows_amd64.exe.zip)
