### ISSUE TITLE
Feature request: Run on startup

### ISSUE THREAD

**Issue by masoncfrancis** [Forceu/Gokapi#147]
I don't think this one would be too difficult to do, just would need to add code to add and enable a systemd service. This'll only work though if the drive Gokapi is running on is mounted on boot, so maybe that should be part of the script as well. This could possibly be enabled with a command line argument, kind of like how VS Code installs their tunnel service

@Forceu would you accept a pull request with this in it if you received one? I'm considering working on it

**Comment by Forceu** [comment]
Hi, yes that sounds like a good idea. I would be happy to merge a PR, I guess the best way would be to add it to the Examples section in the documentation:

https://github.com/Forceu/Gokapi/blob/master/docs/examples.rst

**Comment by masoncfrancis** [comment]
@Forceu Where in the code are arguments defined and used? I looked through but had a hard time finding them

**Comment by Forceu** [comment]
Great to hear!

For anyone else reading this in the future, it can be found at https://github.com/Forceu/Gokapi/blob/master/internal/environment/flagparser/FlagParser.go

**Comment by masoncfrancis** [comment]
I implemented this in PR #152 

Let me know your thoughts. I decided to implement code that does the handling of systemd service stuff for us, instead of making the user do it manually

**Comment by Forceu** [comment]
Added in #152
