### ISSUE TITLE
Bug: issuer did not match the issuer returned by provider when using Authentik

### ISSUE THREAD

**Issue by JeroenoBoy** [Forceu/Gokapi#149]
When I try to setup OID login with Authentik, I get the following error in console after submitting the setup:

`oidc: issuer did not match the issuer returned by provider, expected "https://auth.<redacted>.<redacted>/application/o/gokapi" got "https://auth.<redacted>.<redacted>/application/o/gokapi/"`

This is the post request that gets send:

```json
[
  {"name":"ssl_sel","value":"0"},
  {"name":"logip_sel","value":"0"},
  {"name":"public_name","value":"Gokapi"},
  {"name":"port","value":"53842"},
  {"name":"url","value":"https://share.<redacted>.<redacted>/"},
  {"name":"url_redirection","value":"https://<redacted>.<redacted>/"},
  {"name":"authentication_sel","value":"1"},
  {"name":"auth_username","value":""},
  {"name":"auth_pw","value":""},
  {"name":"auth_pw2","value":""},
  {"name":"oauth_provider","value":"https://auth.<redacted>.<redacted>/application/o/gokapi/"},
  {"name":"oauth_id","value":"<redacted>"},
  {"name":"oauth_secret","value":"<redacted>"},
  {"name":"oauth_recheck_interval","value":"12"},
  {"name":"oauth_restrict_users.unchecked","value":"false"},
  {"name":"oauth_scope_users","value":""},
  {"name":"oauth_allowed_users","value":""},
  {"name":"oauth_restrict_groups.unchecked","value":"false"},
  {"name":"oauth_restrict_groups","value":"true"},
  {"name":"oauth_scope_groups","value":"groups"},
  {"name":"oauth_allowed_groups","value":"Gokapi"},
  {"name":"auth_headerkey","value":""},
  {"name":"auth_header_users","value":""},
  {"name":"storage_sel","value":"local"},
  {"name":"storage_sel_image","value":"nochange"},
  {"name":"s3_bucket","value":""},
  {"name":"s3_region","value":""},
  {"name":"s3_api","value":""},
  {"name":"s3_secret","value":""},
  {"name":"s3_endpoint","value":""},
  {"name":"encrypt_sel","value":"5"},
  {"name":"enc_pw","value":""},
  {"name":"enc_pw2","value":""}
]
```

It might also be worth nothing that I am running this on a TrueNAS scale behind a nginx proxy and installed the application via the TrueCharts catalogue

**Comment by JeroenoBoy** [comment]
I also tried reinstalling the app with the url being "https://auth.<redacted>.<redacted>/application/o/gokapi/" and "https://auth.<redacted>.<redacted>/application/o/gokapi" Both throw the same error

**Comment by Forceu** [comment]
That seems to be an error in your authentic configuration, there shouldn't be a trailing slash at the end of the redirection URL

**Comment by JeroenoBoy** [comment]
I mean, every other application seems to work fine with Authentic, so I just assume the issue is somewhere here

**Comment by JeroenoBoy** [comment]
Then I'm not quite sure what the Provider URL is supposed to be, do you have any clue?

**Comment by JeroenoBoy** [comment]
Oh it seems that the URL is correct, it seems there is an explicit check which breaks it for me. I personally don't think a single "/" should break the entire authentication form. It seems like this issuer check can be omitted with a context option called "skipIssuerValidation"
at: https://github.com/coreos/go-oidc/blob/22dfdcabd450013b4d51ac15b6423f529d957e9f/oidc/oidc.go#L235-L241
I don't have a lot of knowledge about go, but it seems a pretty easy fix. I'll also create an issue @ go-oidc and see if it can be resolved there

**Comment by Forceu** [comment]
Ah I see, sorry I thought it was the redirection URL. Yes, the trimming should not be happening there, I think I put it there by mistake. Thanks for the PR!
