### ISSUE TITLE
Setup asks for S3 credentials, even if set with env variables

### ISSUE THREAD

**Issue by boomam** [Forceu/Gokapi#151]
Hi,  
Current release of 1.8.1, setting of the S3 related environment variables listed [here](https://gokapi.readthedocs.io/en/latest/advanced.html#available-environment-variables) do not get set in app, requiring manual input during the setup wizard.  
I am not sure if this is a bug, or if its a fall back for the [CORS bug](https://github.com/Forceu/Gokapi/issues/72), happy to help investigate though.

Thanks.

**Comment by Forceu** [comment]
Thanks I'll look into it

**Comment by boomam** [comment]
...to expand on the comment in the other issue (#72), im wondering if it *is* setting, just maybe falling back and showing the options in the wizard.
As after a little time, i can see the uploaded files within the s3 bucket.

**Comment by Forceu** [comment]
Changed how setup handles the env variables in 368fb6b. If that does not fix the issue, let me know and I will reopen it.
