### ISSUE TITLE
Question: Failed Uploads

### ISSUE THREAD

**Issue by pablo808** [Forceu/Gokapi#160]
I was just wondering how does Gokapi manage failed uploads? Can the upload be resumed?

Are incomplete uploads deleted off the disk after a certain time to reclaim disk space?

Thanks.

**Comment by Forceu** [comment]
Ah the moment it is not possible to resume uploads (unless you are using the API) and all temporary files are deleted after 24 hours

**Comment by pablo808** [comment]
OK Sounds good. Thank you for the quick reply!
