### ISSUE TITLE
Run Docker container user as root by default

### ISSUE THREAD

**Issue by Forceu** [Forceu/Gokapi#167]
Related to #57 

@Phaeton:
> This can have interesting behavior on the host. The gokapi user is being assigned a low 10# id in the docker build and when the /app folder is chown/chmod, it reassigns the ownership on the host to a existing id there, most likely a systemd service if Debian based. Nothing preventing the application from working, but likely requires root access on host to navigate into the config and data folders and interact.

@MalteMagnussen:

> Yeah, I am seeing some errors on 1.8.3, I wasn't seeing on 1.8.2
> 
> ```
> mhm@mhm:~/Documents/gokapi$ k get pods
> 
> NAME                                      READY   STATUS   RESTARTS   AGE
> wip1-gokapi-deployment-5698466854-wm4qm   0/1     Error    0          2s
> 
> 
> mhm@mhm:~/Documents/gokapi$ k logs deployments/wip1-gokapi-deployment gokapi 
> 
> Setting permissions
> chown: /app/.isdocker: Read-only file system
> chown: /app/data: Operation not permitted
> chown: /app/data: Operation not permitted
> chown: /app/config/config.json: Read-only file system
> chown: /app/config/cloudconfig.yml: Read-only file system
> chown: /app/config/..data: Read-only file system
> chown: /app/config/..2024_05_29_10_42_00.732194877/config.json: Read-only file system
> chown: /app/config/..2024_05_29_10_42_00.732194877/cloudconfig.yml: Read-only file system
> chown: /app/config/..2024_05_29_10_42_00.732194877: Read-only file system
> chown: /app/config/..2024_05_29_10_42_00.732194877: Read-only file system
> chown: /app/config: Read-only file system
> chown: /app/config: Read-only file system
> chown: /app/gokapi: Read-only file system
> chown: /app/run.sh: Read-only file system
> chown: /app: Read-only file system
> chown: /app: Read-only file system
> ```
> 
> I can share the kubernetes yaml, if relevant.

**Comment by MalteMagnussen** [comment]
@Forceu - Here is my current k8s yaml setup, just to share context

A lot of k8s environments nowadays have pretty strict securitycontexts :lock: 

Thanks for this update :muscle: 

[k8s-yaml.zip](https://github.com/Forceu/Gokapi/files/15483659/k8s-yaml.zip)

**Comment by Forceu** [comment]
Implemented in 1.8.4, the docker image should be available in about 30 minutes.
