### ISSUE TITLE
Gokapi accessible only on localhost:53842/login

### ISSUE THREAD

**Issue by Akusho** [Forceu/Gokapi#173]
Hello,
I'm running Gokapi in a docker container, which was initialized with the following parameters:
```
docker run -d \
	-p 53842:53842 \
	--name Gokapi \
	--restart=unless-stopped \
	-e TZ=Country \
	-v /user/Docker/Gokapi/Data:/app/data \
	-v /user/Docker/Gokapi/config:/app/config \
	f0rc3/gokapi:latest
```
During setup, I set the server URL to localhost:53842, with default redirect URL.
My issue is that Gokapi is only accessible on localhost:53842/login. If I try just localhost:53842, it redirects me to github.

I can fix this by setting redirect URL to localhost:53842/login, then it works. The problem with this approach is that I would like to access Gokapi from outside my local network through Cloudflare tunnel. In Cloudflare tunnel I cannot set the server to localhost:53842/login, it doesn't accept a URL with dash after the port.

I have tried playing with the config and server addresses, but I can't get Gokapi to work by accessing just localhost:53842. If I remove the redirect URL it is then stuck in endless loop.
What am I missing?

**Comment by Forceu** [comment]
The UI interface is `localhost:53842/admin`, as output by the logs and stated in the documentation. You can redirect to `/admin` If you prefer that.

**Comment by Akusho** [comment]
> /admin

Thank you so much! Got it. I was redirecting to localhost:53842/admin, but in this case it was not accessible from outside the network.
I set redirect URL to "/admin", and now it works. Awesome, thank you!
