### ISSUE TITLE
Incorrect API Response for File Upload

### ISSUE THREAD

**Issue by adripo** [Forceu/Gokapi#183]
### Description:
When uploading a file using the API, the response includes the following fields: `Url`, `HotlinkUrl`, and `GenericHotlinkUrl`. Each of these fields contains different generic values, but none of them include the file ID.

### Expected Behavior:
The response should contain correct `Url` and `HotlinkUrl` with ID already present.
`GenericHotlinkUrl` should not be provided

### Actual Behavior:
The response provides:

```
  "Url": "https://domain/d?id=",
  "HotlinkUrl": "https://domain/hotlink/",
  "GenericHotlinkUrl": "https://domain/downloadFile?id="
```
All of these fields contain different generic values, but they do not include the file ID.

### Screenshot:

![image](https://github.com/Forceu/Gokapi/assets/26493496/88d7e594-0b1a-4329-b0f8-f1a9317386ec)

**Comment by adripo** [comment]
There is also a `FileInfo` field tagged `HotlinkId` that always has an empty value. I don't think it is necessary

**Comment by Forceu** [comment]
This has been already changed in 6beabdebc325d9f14ab3df0f4d5d62f9c3d9a7b4, but is but released to the stable version yet. They are required for client-side JavaScript.

**Comment by adripo** [comment]
Thanks, do you have any forecast on the release date containing this change? I need to change my scripts contacting the API prior to that update.

**Comment by Forceu** [comment]
Most likely in 1-2 weeks. If you are using Docker, you can already use the image `latest-dev`, it should be stable enough for daily use.
