### ISSUE TITLE
E2E Encryption not initialising

### ISSUE THREAD

**Issue by Forceu** [Forceu/Gokapi#188]
### Discussed in https://github.com/Forceu/Gokapi/discussions/187

<div type='discussions-op-text'>

<sup>Originally posted by **MalteMagnussen** July  5, 2024</sup>
Trying to set up Level 3 End-to-End Encryption: https://gokapi.readthedocs.io/en/latest/setup.html#encryption

But it just "hangs" when it gets to this point. 

![image](https://github.com/Forceu/Gokapi/assets/11192971/18bae5d5-1dca-455f-8374-baa4f0da6ae7)

Nothing in the log about it either. 

</div>

**Comment by Forceu** [comment]
@MalteMagnussen What OS/Browser are you using?

**Comment by Forceu** [comment]
According to the attached logs you are replacing the static folder that contains the JavaScript with a local folder. Can you confirm that the JS file was minified and is correctly loaded?

**Comment by MalteMagnussen** [comment]
@Forceu - The Dockerfile is as follows:

```Dockerfile
FROM company-mirror/gokapi:v1.8.4

COPY ./web/templates/ /app/templates/
COPY ./web/static/ /app/static/

# https://github.com/Forceu/Gokapi/discussions/184#discussioncomment-9871479
RUN mv /app/static/css/cover.css /app/static/css/min/gokapi.min.css
```

The web folder is a copy of the web folder from this repo, with some updates to apply company branding.

**Comment by Forceu** [comment]
Please try if it works if you do not replace the static and template folder. If it does, there is a problem with your configuration and out of scope for this place. Otherwise I offer a paid support plan for commercial users of Gokapi. If your company is interested in this, let me know.

**Comment by MalteMagnussen** [comment]
@Forceu - I ran it with your official image directly, and it works just fine. 

So it seems like there is some change that interferes somehow in our web folder.

**Comment by Forceu** [comment]
Okay, thanks for the reply. Yeah it is weird, that there is no console output, but it is probably a problem with the JavaScript file
