### ISSUE TITLE
Bug: No indication of upload to remote storage

### ISSUE THREAD

**Issue by Forceu** [Forceu/Gokapi#193]
### Discussed in https://github.com/Forceu/Gokapi/discussions/192

<div type='discussions-op-text'>

<sup>Originally posted by **MalteMagnussen** July 22, 2024</sup>
Trying to upload a large file (15GB in this case) to Gokapi causes it to "hang" at the end of the upload.

![image](https://github.com/user-attachments/assets/33c4cfcf-0105-4e4b-97f9-3c6db7a713d1)

It has been several minutes.

We are using S3 as the storage.

We suspect it might be because S3 has to write to "disk/tape" first, and then it sends a link back, and Gokapi is waiting to receive that link, so it can create the row with the links etc. 

Is this a correct assumption? 

Looking at the logs doesn't provide any insights:

```
██████   ██████   ██   ██  █████  ██████  ██ 
██       ██    ██ ██  ██  ██   ██ ██   ██ ██ 
██   ███ ██    ██ █████   ███████ ██████  ██ 
██    ██ ██    ██ ██  ██  ██   ██ ██      ██ 
 ██████   ██████  ██   ██ ██   ██ ██      ██ 
                                             
Gokapi v1.9.0 starting
AWS login successful
Saving new files to cloud storage
Binding webserver to :53842
Webserver can be accessed at https://redacted/admin
Press CTRL+C to stop Gokapi
```

For good measure, here are the `config.json` bits about the chunksize, etc:

```
  "MaxMemory": 50,
  "UseSsl": false,
  "MaxFileSizeMB": 102400,
  "ChunkSize": 45,
  "MaxParallelUploads": 4,
```

And the container resources:

```yaml
          resources:
            limits:
              cpu: 750m
              memory: 1024Mi
            requests:
              cpu: 375m
              memory: 512Mi
```

Smaller sizes working:

![image](https://github.com/user-attachments/assets/1d1e113e-e624-46ac-be24-fe99dc2e9454)
</div>

**Comment by Forceu** [comment]
@MalteMagnussen Thanks for the report, I was able to reproduce it. Normally there should be an indication that the file is being processed / uploaded, I will look into it.

**Comment by Forceu** [comment]
Thanks, there was a problem with the implemented SSE protocol, which was used since the new release. Fixed in 4f71a2b

**Comment by MalteMagnussen** [comment]
@Forceu - Thank you very much. It is much appreciated.

The 15GB.file is showing up in the list of files upon visit to our gokapi instance today. 

Would increasing any of the config give improved performance?  
Could the CPU/MEM be a bottleneck, that if raised to a few GB each, would speed up the processing or upload?

**Comment by Forceu** [comment]
Sorry I just saw your last comment. Hm this should neither be a CPU or RAM limiting task, as by default all files larger than 50MB are written to a temporary file instead of being stored in RAM. 

How long does the upload take? I can image that there is a timeout going on. Unfortunately the JS is not covered by the unit tests, which is why most bugs take place there.

**Comment by MalteMagnussen** [comment]
@Forceu 

Testing a 5GB file upload:

Uploading at speeds between 12MB/s to 15MB/s according to the UI. 

At around 5 minutes and 50 seconds, it was at 100% upload. That makes sense, given the upload speed. 

Then it starts the "Processing" and "Uploading file" step. 

Refreshing the page in a second window, I see the file at 7:30 on my stop watch. So it took ~1 minute and 40 seconds to process the chunks and upload to S3 I assume? Not the end of the world imo. Would just be nice to have the "Uploading file..." step end whenever the file is finished :) 

![image](https://github.com/user-attachments/assets/0313b590-6606-427a-a2bf-4b039b04e2d6)

The supporters in our company have started using the service, and the fact that it **seems** to "hang" on "Uploading file..." is confusing them. Even if they can just open the page in a new tab, and see the file there. 

----

They have also mentioned that when uploading a file with name "Foo", it will always show up as "downloadFile" on the users side. Notice the filename in the UI is correct, but firefox is downloading it as "downloadFile". This is confusing for some customers, as they have trouble unzipping it, if it doesn't keep the .tar.gz extension fx. 

![image](https://github.com/user-attachments/assets/c1564401-9422-4642-a135-9c3e1042f00d)

Something about the `Content-Disposition: attachment;` is not being sent correctly.

**Comment by Forceu** [comment]
Thanks for the feedback! I will track the issue related to the content-disposition in #199. Can you test if this also happens if you do not proxy the file download? I could image that this is where the problem lays.

Normally the file should be added automatically after the upload is complete. I will have a look at it tomorrow

**Comment by MalteMagnussen** [comment]
@Forceu - Thank you very much :) 

Let me check in our test environment what happens if I disable the proxying. 

Will edit here, once I have tested.

**Comment by Forceu** [comment]
@MalteMagnussen The incorrect headers are now fixed in the latest dev version. I will have a look at your problem that the new file is not displayed in time later on.

**Comment by MalteMagnussen** [comment]
@Forceu - Thank you very much. 

It is working now in our test and prod environments.
