### ISSUE TITLE
Bug: URL's after upload showing 'undefined' / Old JS version is still cached

### ISSUE THREAD

**Issue by abramter** [Forceu/Gokapi#195]
Hello,

So not sure if this has been seen before or not, but on my v1.9.0 which is setup using Docker, I am getting this bug once I upload a file. When the file finishes uploading, and the system shows you the 'Copy URL' or 'Copy Hotlink' buttons, once clicked I see this.

` undefinedz29d7hoQabJOZOg `

![Screenshot_1](https://github.com/user-attachments/assets/2452c1eb-3857-4643-a1ad-7997c4c4b0d1)

![Screenshot_2](https://github.com/user-attachments/assets/b17156e0-b7ab-495b-b9b6-3aef37d9f012)

Once I refresh the admin page, the links are displayed correctly.

**Comment by Forceu** [comment]
Hi, it seems that the old Javascript is still loaded. Does the error still appear if you reload without cache by pressing Ctrl+F5 to refresh the page?

**Comment by abramter** [comment]
> Hi, it seems that the old Javascript is still loaded. Does the error still appear if you reload without cache by pressing Ctrl+F5 to refresh the page?

Yup that did it, seems like my browser wasn't clearing the old stuff even thou i forced it once I upgraded, thank you for the help.

**Comment by Forceu** [comment]
Great to hear it is working now. Weird that the file was still cached, I did increase the version number, so it should have been reloaded... I will look into it.

**Comment by Forceu** [comment]
I changed the versioning in f08490e, now caching should not be a problem anymore for new versions
