### ISSUE TITLE
[question] When I upload a file to gokapi, It response 404 

### ISSUE THREAD

**Issue by rogerBridge** [Forceu/Gokapi#20]
Hello sir, I face a problem, when I deploy your elegant App on my VPS, I found this question, when I upload some file to gokapi app, I always face a error: "Server respond with a 404 error code", I check alll my settings, but I can not found the cause;

platform: debian 10 + docker 19.03.12;
web server: caddy v2.1.1
reverse proxy set: 
```Caddyfile
route /gokapi/* {
                uri strip_prefix /gokapi
                reverse_proxy 127.0.0.1:53842
        }
```
I can viste the web page normally, but only when I upload file, the error appear;
If you need more log, please tell me, thank you very much, thank you for your elegant app;

**Comment by Forceu** [comment]
Thanks, fixed in 5068b742aaf22cfa5341c7dbd76449b8521310f8

The docker image `latest-dev` should be up in a few minutes, which will contain the fix.
