### ISSUE TITLE
Docker Setup screen doesnt fit browser window

### ISSUE THREAD

**Issue by truthsword** [Forceu/Gokapi#205]
![](https://i.imgur.com/GF792ow.png)
There is no option to scroll up, and reducing browser magnification does not reveal the full setup window. 

Later, nearing setup completion there is this:
![](https://i.imgur.com/g0xOIno.png)

However there is no apparent console entry, so one can only enter "Continue".

**Comment by Forceu** [comment]
Hi, thanks for the feedback! What is your display resolution?

The password has to be entered in the console of the application / container. Are you using Docker?

**Comment by truthsword** [comment]
2880x1620

**Comment by Forceu** [comment]
Unfortunately I am unable to reproduce the problem, even when trying multiple resolutions. I will close this for now, as the setup can still be completed. If anyone else has the same problem, please report here
