### ISSUE TITLE
Feature: Update download count live (without page refresh)

### ISSUE THREAD

**Issue by yonas** [Forceu/Gokapi#206]
It would great to have the download count automatically updated without manually refreshing the page.

## Ideas

Add some Javascript that creates a websocket connection with the server.

When the server [increments the download count](https://github.com/Forceu/Gokapi/blob/0e80a59e1573da1cb866bbcce9c47ec2c7afaec3/internal/storage/FileServing.go#L524), loop through all the open websocket connections and send a JSON message, like `{ "downloadCount": ... }`.

**Comment by Forceu** [comment]
Added in d215994
