### ISSUE TITLE
[ feature request ] Unattended installs

### ISSUE THREAD

**Issue by yonas** [Forceu/Gokapi#207]
It would be great simply run ./gokapi the first time and have a fully functional file server.

Suggested sane defaults:
- database: SQLite
- authentication: generate a username/password and print to console, or none
- encryption: end-to-end or none [ not sure ]
- bind address: localhost
- storage: local

**Comment by Forceu** [comment]
Thanks for your feedback! This is already possible, see https://gokapi.readthedocs.io/en/latest/advanced.html#automatic-deployment

**Comment by yonas** [comment]
> ... You will need to complete the setup on a temporary instance first.

@Forceu Perhaps we can add a `init` command that would dump a bare-bones config that works, and sets an empty password.
