### ISSUE TITLE
Documentation: replace instances of "Bare metal"

### ISSUE THREAD

**Issue by paranoikthecat** [Forceu/Gokapi#208]
Please replace instances of "bare metal" in documentation with "Windows" or "Linux" or "OS" or something to your liking.

What you're referring to isn't "bare metal", it's "OS". Bare metal means "directly on hardware without an OS", not "everything that's not Docker". Current version of documentation may mislead developers looking for bare-metal software.

https://en.wikipedia.org/w/index.php?title=Bare_metal

**Comment by Forceu** [comment]
Thanks for the feedback. I will update this with the next version

**Comment by Forceu** [comment]
Changed in #208
