### ISSUE TITLE
Starting Docker image errors

### ISSUE THREAD

**Issue by irate-badger** [Forceu/Gokapi#3]
Performing the initial startup of the Docker image, it appears that it expects a configuration file to already exist or it is prompting the user, but with Docker we don't have that prompt presented.

Might just be a documentation update to show to do that.

**Comment by Forceu** [comment]
Thanks for the report. Did you use the `-it` parameter as stated in the documentation? I only tested it with podman, but it should work with docker as well. I will probably add a note that the -it is required

**Comment by irate-badger** [comment]
I'm really sorry. I missed that you were supposed to run it in interactive mode first. That works great! 

Thank you, I'm going to start using this.

**Comment by Forceu** [comment]
No worries :) Nevertheless thanks for the issue, otherwise I would not have added the note to the Readme.
