### ISSUE TITLE
Docker Image not using data dir during upload

### ISSUE THREAD

**Issue by rix1337** [Forceu/Gokapi#37]
This tool is awesome and mostly works for me. During uploading a larger file I noticed, my docker system almost running out of space.
I have set the data dir to a folder on my docker host, so this is unexpected.
Only after fully uploading the file, does it get transfered from within the docker container to that external folder.

This should not be happening:
![grafik](https://user-images.githubusercontent.com/9930448/147850599-49278a3b-dcfd-4095-acd2-b371b949356f.png)

**Comment by Forceu** [comment]
Normally the temp file should be stored in the data directory as well. What are your values for `DataDir` and `MaxMemory` in your config.json?

**Comment by rix1337** [comment]
Yup, can confirm it works if I set the TMPDIR to equal the datadir.

**Comment by rix1337** [comment]
Thats actually a valid workaround or something you can bake into the official docker image by default withouth touching Gokapi itsel.f

**Comment by Forceu** [comment]
Great to hear it is working and thanks for raising the issue! It has been added to eb609e so that the Docker images create the temp files in the data directory by default.

Happy new year! :)
