### ISSUE TITLE
Feature Request: Sqlite config backend

### ISSUE THREAD

**Issue by AlekseyLobanov** [Forceu/Gokapi#39]
Hello.

Storing files and sessions inside config is not great idea for several reasons:
1. It's not secure, because read-only access for configs in Linux is a common practice.
2. It's not good for performance beacuse full rewrite required.
3. It's, in general, bad practice.

What do you think about adding new backend. Sqlite will be the simplest one, which can be used for existing configs, mostly, inplace (for example, another `.sqlite` file in config folder). Also supporting sqlite may lead to supporting normal DBs like Postrgres or MariaDB.

Benefits:
1. May increase performance and stability with low-end devices with bad IO which is may relevant for this application.
2. May increase performance for instances with a lot of files, because config rewrite is not required (adding 1 file to 10000 existing is not a problem)
3. State isolation is a good technique  in general. Many self-hosted application can store almost full state in DB, except user data. And one DB backup script is enough for server backup, but another procedure is required for gokapi

What do you think? I also can help with this if you wish.

Regards.

**Comment by Forceu** [comment]
Yes, sqlite is definitely on my todo list and will be added with the next release. I am however currently working on file encryption which will be finished first.

At the moment it is not a performance factor, as the configuration is stored in memory and the write to the config file is a non blocking action in a background thread. 

The problem with sqlite on go is that it requires C code, which makes cross-compiling a little bit more difficult. The only project I found that does not rely on C was https://pkg.go.dev/modernc.org/sqlite - I will probably give that a try (even if that means dropping the Windows 386 platform)

**Comment by AlekseyLobanov** [comment]
>non blocking action in a background thread

In this case we can still have some problems with poor IO devices. Like big delays between file uploading and adding it to config. Also full file rewrite still required.

Can I help with it or some other useful tasks? Do you have something like backlog?

**Comment by aanderse** [comment]
I was going to file my own issue but saw this one which is related, so I'll just comment here.

> Storing files and sessions inside config is not great idea

I was going to ask for a separate config file from session file. I wasn't concerned where the session data was stored (flat file, sql), just that it be separate from configuration so I can make my configuration file read-only.

Thank you for such a wonderful piece of software!

**Comment by Forceu** [comment]
Thanks for your input! At the moment my plan is to have three files: A config file and two key-value databases for sessions and data. I might also include redis support for the key-value storage. This will be done after encryption is finished, which will probably take a couple of weeks.

May I ask what your use case for a read-only config file is?

**Comment by aanderse** [comment]
@Forceu that sounds great!

> read-only access for configs in Linux is a common practice.

I support that as a general policy.

Specifically my use case is that I want to package and run this software on [NixOS](https://nixos.org/) and provide the configuration file declaratively, which in NixOS means immutable. NixOS is a whole philosophy on declarative and reproducible systems which makes extensive use of immutable (at run time) configuration.

Thanks again!

**Comment by AlekseyLobanov** [comment]
>also include redis support for the key-value storage
I am sorry but why Redis as a storage? Redis is fast but it is in-memory, not persistent. Even with `.rdb`

**Comment by Forceu** [comment]
Redis can be configured to be persistent.In the end I decided to use a Go-native key-value database, a draft that already stores sessions and other configurations in the database can be found at #40

**Comment by Forceu** [comment]
It should be fully implemented now, #40 has been merged. Please compile the latest commit or try the docker image `latest-dev` which should be up in about 10 minutes and let me know if it is working for you :)
