### ISSUE TITLE
File too large error

### ISSUE THREAD

**Issue by Pantar2205** [Forceu/Gokapi#42]
Docker install as per Documentation.

Tested first with a 53mb file > No issues, works as expected.

Testing with a 4gb windows.iso > Below error is shown. Same error in Firefox & Google Chrome.

![image](https://user-images.githubusercontent.com/43005360/151661856-f35d40ae-e4d5-4662-9d0a-30c8483fb0cb.png)

**Comment by Pantar2205** [comment]
SOLVED : cloudlfare upload limitation. nothing to do with gokapi

**Comment by Forceu** [comment]
Unfortunately that is a known problem which will be solved once chunked uploads is added #12

**Comment by Forceu** [comment]
Chunked uploads added in 44260f012b59e58240a9a1f2de8ae45cbf60e13b
