### ISSUE TITLE
Custom Templates - apiKeys url linked incorrectly

### ISSUE THREAD

**Issue by asd913** [Forceu/Gokapi#43]
I am using the latest-dev branch as I needed passwords to work through the API. When I tried to customize the pages, I copied the templates folder to my own location. After loading the container with the local templates folder, the API link on the admin page would lead to an error 403.

In the templates folder, I found out the issue is that in the file html_header.tmpl, the link for the API goes to ./api. It should be linking to ./apiKeys. It was an easy fix but still something I wanted to bring to your attention.

**Comment by Forceu** [comment]
Thanks for the issue! It seems like you did not copy the templates from the current master branch, as it is correct in the current copy:

https://github.com/Forceu/Gokapi/blob/a2daccd97228fceda6a2656d575a4ab143b4ef30/internal/webserver/web/templates/html_header.tmpl#L47

However if you find any other broken links let me know!
