### ISSUE TITLE
Enhancement: some pastebin functionality

### ISSUE THREAD

**Issue by AlexFullmoon** [Forceu/Gokapi#45]
Would be useful to either copypaste text or at least show text files content.

Sort of what [linx-server](https://github.com/andreimarcu/linx-server) does.

**Comment by Forceu** [comment]
Thanks I will keep that in mind! Linx-server looks very interesting as well, I will have a closer look at that and maybe copy some functions.

**Comment by Forceu** [comment]
In the latest release you can paste text, however I decided that viewing text will be out of scope, therefore I am closing this for now. If anyone else would like to see this feature, please comment below :)
