### ISSUE TITLE
Allow unlimited downloads through API

### ISSUE THREAD

**Issue by trolley** [Forceu/Gokapi#46]
From what I can tell you either need to provide an `allowedDownloads` value when uploading via the `add` API or it will default to the last value from the web interface. Though the web interface you can turn off the allowed downloads to allow unlimited downloads, but you can't do the same thing through the API.

Could `allowedDownloads` take a value like `0` or `-1` to indicate unlimited downloads?

**Comment by Forceu** [comment]
Thanks, I did indeed forgot to change the API! I'll add it later today
