### ISSUE TITLE
Feature Request: Show amount of downloads for unlimited files

### ISSUE THREAD

**Issue by iplusplus42** [Forceu/Gokapi#53]
It would be quite helpful if I could see the number of downloads for files without download limits. Since just putting the number of downloads into the "Downloads remaining" column wouldn't make much sense, I was thinking that a sensable change would be to rename the column to something like "Downloads/Limit" and change each row to "x/limit" for files with download restrictions or "x/Unlimited" for files without restrictions. Thank you!

**Comment by Forceu** [comment]
Thanks for the feedback, I will probably add a new column with the download count.

**Comment by iplusplus42** [comment]
Thank you for the quick response! I agree that a new column would make the most sense. When creating the feature request, I wanted to present the idea with as minimal of a change as possible. Thanks again for considering this feature! Have a great day!

**Comment by Forceu** [comment]
Added in 057709a794ff43308d0d283f9a5f2f915c7a439b

**Comment by iplusplus42** [comment]
Well dang, I didn't expect you to implement it that quickly! I should strive to complete the issue lifecycle this quickly for my own projects! Thank you so much!

**Comment by Forceu** [comment]
Haha thanks! It took only five minutes to implement though
