### ISSUE TITLE
Switch from root user in Docker image?

### ISSUE THREAD

**Issue by sfkpmr** [Forceu/Gokapi#57]
Would it be possible to change that the Docker container runs as root in case of container escapes?

I gave it a quick try to run it as nobody, but the setup fails to complete and logs show:

"http: panic serving my_ip:61273: mkdir config: permission denied"

**Comment by Forceu** [comment]
Thanks, I will have a look once I have the time. Personally I am using podman where the container doesn't run as root

**Comment by vidschofelix** [comment]
add `user: 1000:1000`, or any uid:gid you want to use to your docker-compose file. 
after first start chown the config and data folder to the corresponding uid:gid, f.e. `sudo chown -R 1000:1000 config/ data/`, then `docker-compose restart` and you are good to go 👍

**Comment by Forceu** [comment]
Added in edd5ecf, no migration will be required
