### ISSUE TITLE
No matching manifest for linux/arm64/v8

### ISSUE THREAD

**Issue by kokoparkletal** [Forceu/Gokapi#59]
Trying to install Gokapi in docker on an oracle ampere server I get the following error (as usual on arm64...):

`docker: no matching manifest for linux/arm64/v8 in the manifest list entries.`

Any workarround?

**Comment by Forceu** [comment]
Was originally added in e96f8bb02e781f8c66d1b34d6ec049e6dddb8557, but as no release was published, it only applied to the `latest-dev` image.

With today's release of 1.5.2 arm64 should be supported with the regular `latest` image.
