### ISSUE TITLE
 Excessive (executable) file's permissions for non executable files

### ISSUE THREAD

**Issue by CompuRoot** [Forceu/Gokapi#60]
## Environment

|Item|description|
|:-----|:----:|
|`gokapi`| **Ver:** 1.5.1 |
|Host| Linux amd64|

## Files with insecure permissions 

|file|current permission| should be|
|:---|:---:|:---:|
|`./config/ssl.crt`| 700 | 600 |
|`./config/ssl.key`| 700| 600|
|`./data/filestorage.db/meta.json`| 700| 600|

## Also, suggestion to set more secure permissions on log and uploaded content
`./data/log.txt`      
as well uploaded blobs (filenames as hashes) should have permissions 600 instead of 644

**Comment by Forceu** [comment]
Thank you for your issue! As the `data` folder has the permission `700`, it is not a serious security risk for now, as the data with permissions `644` is still unreadable for unauthorised users. I will change that with the next commit.

`./data/filestorage.db/meta.json` is created by a library, I would rather not change the permission manually, as is having the executable bit is not really a big concern.

I will change the ssl certificate permissions however.
