### ISSUE TITLE
Feature Request: Copy directlink for non image files (button)

### ISSUE THREAD

**Issue by Jisagi** [Forceu/Gokapi#62]
Hi, would it be possible to add a fourth button to be able to copy the direct link to a non image file? This would make it easier to download files in a console. I currently create the link manually with `https://host.tld/downloadFile?id=<ID>`.

It does not necessarily have to be another button, but a possibility in general to copy the above link in the frontend. On that note, you could also add `DownloadUrl` to the json response when uploading via the api, so custom upload scripts can use it as well.

**Comment by Forceu** [comment]
Thanks for the feedback! Yes that sounds good, I will put it on my todo list.

**Comment by Forceu** [comment]
Added in 882ddd4. You can test it by compiling the current master branch or by using the `latest-dev` docker image.

**Comment by Jisagi** [comment]
Wow, that was fast. Thank you very much for adding this!

**Comment by Forceu** [comment]
No problem, it was not a lot of work to implement. Please note however, that the Json response does not show a hotlink URL, only a generic one (`https://host.tld/downloadFile?id=`). A script would need to check if `item.RequiresClientSideDecryption` is false and `item.PasswordHash` is empty, and in that case append `item.Id` to the generic hotlink.

In the future I will probably enhance the Json output, so this is done automatically (and also remove some values, e.g. the encryption parts).
