### ISSUE TITLE
Setting up on Digital Ocean etc..  W/O Direct LAN access

### ISSUE THREAD

**Issue by bikrdotnet** [Forceu/Gokapi#70]
Is there a way to configure this w/o having direct lan access? I only have SSH access to my droplet and it's asking me to visit the lan IP of the machine. Attempting to visit the WAN IP gives me a "this site is in maintenance mode" message.   Any help would be greatly appreciated.

**Comment by Forceu** [comment]
Yes, it is possible with the current version. You can simply visit the URL http://yourwanip/setup to finish the setup. Let me know if that is working for you.

**Comment by bikrdotnet** [comment]
Interestingly it did let me setup but once the setup was done and it asked me to connect to /admin the connections just hang.   I set the port to 80 , there are no other services running currently on that instance using that port.  Restarting the service doesn't seem to help:

`
██████   ██████  ██   ██  █████  ██████  ██ 
██       ██    ██ ██  ██  ██   ██ ██   ██ ██ 
██   ███ ██    ██ █████   ███████ ██████  ██ 
██    ██ ██    ██ ██  ██  ██   ██ ██      ██ 
 ██████   ██████  ██   ██ ██   ██ ██      ██ 
                                             
Gokapi v1.5.2 starting
Saving new files to local storage
Binding webserver to :80
Certificate is valid for 365 days. A new one will be generated 7 days before expiration.
Webserver can be accessed at https://*.*.*.*/admin
Press CTRL+C to stop Gokapi`

**Comment by Forceu** [comment]
If you are using SSL, you will need to set the port to 443 or specify the port after the URL e.g. https://1.1.1.1:80/

**Comment by bikrdotnet** [comment]
What's the quickest way to reset the config?  Setting the port manually to 80  with https://1.1.1.1:80/admin is still hanging fwiw.

**Comment by Forceu** [comment]
There should be a new subfolder named config which contains the configuration. You can simply edit that file with a texteditor and restart the server.

**Comment by bikrdotnet** [comment]
Found / Edited - Changed to port 443 / For some reason still just hanging trying to connect then times out.  Weird.  

`Gokapi v1.5.2 starting
Saving new files to local storage
Binding webserver to :443
Certificate is valid for 365 days. A new one will be generated 7 days before expiration.
Webserver can be accessed at https://67.205.141.37/admin
Press CTRL+C to stop Gokapi
`

**Comment by Forceu** [comment]
So I just tried setting up Gokapi on a DO droplet and it worked without any problems. I noticed however that if you install it with Docker, the internal Docker IP address is displayed in the setup instead of the external IP. Please double check your IP address. You can also rerun the setup with the `--reconfigure` argument

**Comment by bikrdotnet** [comment]
So strange..  443 and 80 are def allowed but it just rejects the connections...

**Comment by bikrdotnet** [comment]
Just started a brand new droplet to start over.  I'm able to get through the setup wizard and setup my port etc...  I also made sure to allow the port via UFW and once I save the config and try to hit the site on root or /admin it just spins and then times out. (can't be reached).   So strange.   Any way to debug and see if it's trying to make the connection?

**Comment by Forceu** [comment]
Are you using the binary or docker?

**Comment by bikrdotnet** [comment]
Docker / but happy to get this going anyway possible. :)

**Comment by bikrdotnet** [comment]
Ah , so I'm cranking closer to a solve....   If I leave the port as default it does seem to work (regardless of my fixing firewall the other ports don't).  I left it as 53842 and we are working.   

I attempted switching to auth type 1 from 0 and integrating with Onelogin custom connector but ran into some issues there.  I'll fuddle with it and see if we can get it going.

I do have a question / where do the files exist to edit the style etc?  Also can we have the site live in root vs /admin ?

**Comment by Forceu** [comment]
If you are using docker, you need to leave the port on default during the setup (the current unstable version already doesn't let you change the port). You can then map the gokapi port to 80/443 by changing the `-p` argument during container creation.

The ui can be changed, see https://gokapi.readthedocs.io/en/latest/advanced.html#customising
