### ISSUE TITLE
No timeout for connecting to cloud storage

### ISSUE THREAD

**Issue by maltegrosse** [Forceu/Gokapi#72]
I run into two issues setting minio storage as a cloud s3 backend.

1.  Using a non valid Endpoint (URI) leads to endless validity check without timeout (perhaps a timeout function can be passed, see https://github.com/Forceu/Gokapi/blob/master/internal/storage/cloudstorage/aws/AwsS3.go#L53 )
2. I assume Minio does not provide cors settings per bucket by default  - by using "test configuration" during the setup stage, following error appears: `Could not check CORS settings. Error: NoSuchCORSConfiguration: The CORS configuration does not exist`. The Cors Allow Origin Policy per Minio Server is set to `*` . Is it possible to disable the `IsCorsCorrectlySet` or just let it run as a debug log?

**Comment by Forceu** [comment]
Thanks I added a timeout in a8cbf2b25cb09a1023745ad24a2c23170e56d0a1 - according to the AWS SDK documentation there should have been a timeout by default, but it appears that this was for v2 of the SDK.

Regarding the CORS check, I added a parameter to disable it in 844dd350c402380ad1a81a4b5323b93f13486b38

**Comment by maltegrosse** [comment]
@Forceu thank you for the fast PR - is any stable release planned?

**Comment by Forceu** [comment]
Yes, as soon as end-to-end encryption is completed, a new version will be released. If you are using docker, you can use the `latest-dev` image.

**Comment by boomam** [comment]
This issue unfortunatelly persists.  
Is there a workaround?

**Comment by Forceu** [comment]
I'll look into it. How can I reproduce the problem?

**Comment by boomam** [comment]
Hi,
During the setup wizard, configure an S3 connection to Minio, and you get the same CORS related error as above.
Interestingly though, flipping back to local storage and continuing, looking at Minio regardless, files do get put there after a period of time, so perhaps this and #151 are somewhat related?

Perhaps it is setting the env variables, but the initial CORS issue creates a fallback perhaps in the wizard?

**Comment by Forceu** [comment]
I updated the setup in 368fb6b, if you are using docker you can test it with the `latest-dev` image, which should be built in about 20 minutes. Let me know if that solves the issue, or if there is more to it.

**Comment by maltegrosse** [comment]
I just found time to test it again (latest stable release) - for me on kubernetes its hard too set that flag - can the flags be replaced by environment variables? (couldnt find something in the documentation)

anyhow, ignoring the CORS error messages during wizard, the main application runs with minio without any visible error messages

**Comment by Forceu** [comment]
Thanks for the feedback! I added the env variable `GOKAPI_DISABLE_CORS_CHECK`  to disable the CORS check in 729185f
