### ISSUE TITLE
Feature Request: Oauth: Allowed Groups

### ISSUE THREAD

**Issue by maltegrosse** [Forceu/Gokapi#73]
instead of limiting the access to certain users, restrict the access to certain groups would be helpful. perhaps using the non-standard? groups claim.

https://github.com/Forceu/Gokapi/blob/49f11e94dab4762bb16d13762a67d43c858ace67/internal/webserver/authentication/Authentication.go#L78

**Comment by Forceu** [comment]
Sounds like a good idea!

**Comment by Forceu** [comment]
Implemented in 9083ac3d05e5fdc77e9d66b7b8fbafcb65c125c2
