### ISSUE TITLE
Infinte loop with authelia header auth

### ISSUE THREAD

**Issue by Hannsre** [Forceu/Gokapi#74]
Hello,

I guess it's me being stupid, but I can't seem to get authelia header auth to work with gokapi. 
Authelia seems to work fine otherwise, even with gokapi when set to basic authentication. 

The moment I authenticated my browser won't stop reloading, alternating between /login and /admin. I did check with different browser and devices.

All I get in the gokapi logs is:
```
2022/07/30 14:09:08 http: TLS handshake error from 172.17.0.1:35536: EOF
2022/07/30 14:09:10 http: TLS handshake error from 172.17.0.1:35628: EOF
```

And authelia logs: 
```
time="2022-07-30T16:02:10+02:00" level=debug msg="Check authorization of subject username=hannes groups=admins,dev ip=10.10.1.103 and object https://my.domain/login (method )."
time="2022-07-30T16:02:10+02:00" level=debug msg="Check authorization of subject username=hannes groups=admins,dev ip=10.10.1.103 and object https://my.domain/favicon.ico (method )."
```
Before it fails I get a succesful authentication:
```
time="2022-07-30T16:09:06+02:00" level=debug msg="Mark 1FA authentication attempt made by user 'hannes'" method=POST path=/api/firstfactor remote_ip=10.10.1.103
time="2022-07-30T16:09:06+02:00" level=debug msg="Successful 1FA authentication attempt made by user 'hannes'" method=POST path=/api/firstfactor remote_ip=10.10.1.103
time="2022-07-30T16:09:06+02:00" level=debug msg="Check authorization of subject username=hannes groups=admins,dev ip=10.10.1.103 and object my.domain/login (method )."
time="2022-07-30T16:09:06+02:00" level=debug msg="Required level for the URLmy.domain/login is 1" method=POST path=/api/firstfactor remote_ip=10.10.1.103
time="2022-07-30T16:09:06+02:00" level=debug msg="Redirection URL my.domain/login is safe" method=POST path=/api/firstfactor remote_ip=10.10.1.103
```
I followed the setup according to the docs and set it to header auth set to `Remote-User`. I tried with and without creating a local ssl cert.

Im running nginx proxy manager if that's important, setup authelia[ with this guide](https://thehomelab.wiki/books/dns-reverse-proxy/page/setup-authelia-to-work-with-nginx-proxy-manager).

I'm not really sure what to check next, google isn't much help sadly.

**Comment by Forceu** [comment]
According to the attached Gokapi logs it is a problem with the SSL connection. Have you enabled SSL with Gokapi? If you are using a reverse proxy, it is better to use plain HTTP and do the SSL encryption with the reverse proxy.

**Comment by Hannsre** [comment]
thanks for replying. It was in fact me being stupid! I checked again without SSL (tried that before as well) and only got a 503 like before. Turned out I had a wrong custom location in NPM that messed everything up. Now it works as intended, thanks again!
