### ISSUE TITLE
Feature Request: Add permission model to API keys

### ISSUE THREAD

**Issue by Forceu** [Forceu/Gokapi#79]

**Comment by mwild1** [comment]
The main thing of value to me would be to prevent an API key from being able to enumerate files. Assuming the IDs are unpredictable, this would limit an attacker with an exposed API key to being able to upload and download stuff (that it already knows about). It wouldn't leak existing files to the attacker.

Right now I'm faced with all files being accessible if my API key leaks, even though I only use the API for uploading stuff.

**Comment by Forceu** [comment]
Added in c68afac
