### ISSUE TITLE
Issue: config.json - unexpected end of JSON input

### ISSUE THREAD

**Issue by tmeuze** [Forceu/Gokapi#80]
Hello, 

I'm hoping I can get some support, but I'm running this [Unraid template](https://forums.unraid.net/topic/117122-support-smartphonelover-gokapi/) - so I can't be certain my issue can be solved here. The template is essentially Gokapi v1.6.1 using docker-compose. 

My configuration used to work, until a recent update - not sure which. Now, I cannot start the container, and am left with `error reading config.json: unexpected end of JSON input` in the log. I deleted my `config.json` and started over using the newish onboarding wizard (which is really nice btw), but I'm still getting this error. 

I don't see anything wrong with the configuration, but maybe I'm missing something.

`config.json`:
```
{
  "Authentication": {
    "Method": 1,
    "SaltAdmin": "<redacted>",
    "SaltFiles": "<redacted>",
    "Username": "",
    "Password": "",
    "HeaderKey": "",
    "OauthProvider": "https://authentik.domain.tld/application/o/gokapi/",
    "OAuthClientId": "<redacted>",
    "OAuthClientSecret": "<redacted>",
    "HeaderUsers": null,
    "OauthUsers": null
  },
  "Port": ":53842",
  "ServerUrl": "https://g.domain2.tld",
  "RedirectUrl": "https://domain2.tld",
  "ConfigVersion": 12,
  "LengthId": 10,
  "DataDir": "data",
  "MaxMemory": 40,
  "UseSsl": false,
  "MaxFileSizeMB": 102400,
  "Encryption": {
    "Level": 0,
    "Cipher": null,
    "Salt": "",
    "Checksum": "",
    "ChecksumSalt": ""
  },
  "PicturesAlwaysLocal": true
}
```

Thank you for any help you can provide.

**Comment by Forceu** [comment]
Thanks for your feedback! Did you accidentally remove the quotation mark for `OAuthClientSecret` or was it indeed missing? And does the value of `OAuthClientSecret` contain a quotation mark?

**Comment by tmeuze** [comment]
Hi there, thank you for the awesome project! 

That was a mistake in typing on GH, my bad. There is indeed a closing quotation mark, and no quotation mark in the actual value. I have edited my original comment.

**Comment by Forceu** [comment]
Sorry for the late reply. Hm that is rather weird in that case. Do the redacted parts contain any special characters?

**Comment by tmeuze** [comment]
No worries! No special characters in any of the redacted hashes. I just reran the onboarding wizard, and chose local auth, and the same issue persists. I see that the config file is written as soon as this error appears, after submitting:
![CleanShot 2022-08-29 at 17 28 42](https://user-images.githubusercontent.com/9298659/187302952-45eee448-4200-4a08-bc25-8c249f866ef2.png)

The container will only stay up immediately after writing the config. Once stopped, it refuses to start again. 

Thank you again. Maybe I am at the mercy of the Unraid template maintainer here.

**Comment by Forceu** [comment]
Okay that is very strange, does it happen as well if you run the setup with the default values? If yes there might be indeed something wrong with the unraid template...

**Comment by tmeuze** [comment]
I've tried a standard docker compose as well, but the same thing happens. I don't know what it could be, but it must have something to do with Unraid. 

Thank you for your time.
