### ISSUE TITLE
[Question/Bug] Running in k8s, WebserverPort error

### ISSUE THREAD

**Issue by TheAnachronism** [Forceu/Gokapi#84]
Hey there,

I'm trying to run this inside k8s, and I don't know how you do it but from somewhere you get an address gokapi binds itself to and inside a k8s pod it cannot get a correct address.
The specific error I get on startup is:
```logs
Error parsing env variables: env: parse error on field "WebserverPort" of type "int": strconv.ParseInt: parsing "tcp://10.43.45.31:53842": invalid syntax
```

I guess it should be `http://xxxx:port` instead of `tcp`.
Is there some kind of configuration possibility to force gokapi what it should bind to?

**Comment by Forceu** [comment]
Sorry for the late reply. It looks like you are passing the environment variables, `GOKAPI_PORT` should only be an integer. Can you please check what the env variables for this pod are?

**Comment by TheAnachronism** [comment]
I overwrote the startup command for the container to print out all env variables and this is what came back:

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=gokapi-865747f6bb-8z6zv
GOKAPI_PORT=tcp://10.43.98.242:53842
GOKAPI_PORT_53842_TCP_PORT=53842
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1
GOKAPI_SERVICE_PORT=53842
GOKAPI_PORT_53842_TCP_ADDR=10.43.98.242
KUBERNETES_SERVICE_HOST=10.43.0.1
KUBERNETES_PORT=tcp://10.43.0.1:443
GOKAPI_SERVICE_HOST=10.43.98.242
GOKAPI_PORT_53842_TCP=tcp://10.43.98.242:53842
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT_443_TCP_PORT=443
GOKAPI_PORT_53842_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443
HOME=/root
```

**Comment by Forceu** [comment]
Yeah these look really weird. Are you using a 3rd party script for the k8 pod? Make sure that `GOKAPI_PORT` is set to `53842` instead of `tcp://10.43.98.242:53842`

**Comment by TheAnachronism** [comment]
OK, specifying the port has solved the startup problem, and I was able to configure it. Thank you!!
