### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by tomasandrle** [Forceu/Gokapi#85]
Here's a humble suggestion to improve the design of uploaded items.

1. Not enough space for full filename
2. Slight overlap between progress bar and filename
3. Size units can stay in MB until file size actually reaches 1GB

<img width="2168" alt="gokapi-upload-item" src="https://user-images.githubusercontent.com/42672549/201788649-61e797e8-d86c-44f6-b6ee-93b9d9c49545.png">

**Comment by Forceu** [comment]
Yes, I am aware that the current progress view isn't ideal and my plan for the future is to write an own component instead of relying on the library's view.

This would also include a status once the file is completely uploaded, but still processed server-side.

**Comment by Forceu** [comment]
Added in 246b3f5edc10fa0314df1d525e1fd1b7c394c542
