### ISSUE TITLE
Upload drop zone malfunction when using a static local folder

### ISSUE THREAD

**Issue by DJBootyShark** [Forceu/Gokapi#87]
So after setting Gokapi up with e2e encryption whenever I use a local static folder rather than the internal one the upload drop zone freezes on "Loading end-to-end encryption..."

Deleting the static folder and then restarting the service fixes the problem.

It happens when you use both template and static folders but if you delete the template folder it persists.

I noticed another weird thing which is when you clear your site data it prompts you to put in the encryption key after logging in, as normal, but when you press the button to submit nothing happens.

**Comment by Forceu** [comment]
Thanks for the issue. Can you please post the error output on the console for both problems (you can normally open it by pressing F12 in your browser)? Also is the modified source you are using based on the same Gokapi version (according to the [documentation](https://gokapi.readthedocs.io/en/latest/advanced.html#customising))?
