### ISSUE TITLE
Error processing files on Windows systems

### ISSUE THREAD

**Issue by SilentSpartan** [Forceu/Gokapi#95]
When trying to upload any file, I get the following error:
![1](https://user-images.githubusercontent.com/11543839/227775505-e0da07e8-2408-4f01-9a60-5b06bcebbea0.png)

It is saying the files are being used by another process when it isn't. I've tried looking for a solution but can't seem to find anything.

Any suggestions?

Thanks

**Comment by Forceu** [comment]
Interesting. Are you using Docker or are you using the executable? And are you sure, that only one process is running? Does that happen with all files and does it also happen after restarting Gokapi?

**Comment by SilentSpartan** [comment]
I'm using the 64 bit Windows executable. I'm using Windows 10. It happens with ANY file I try. It does happen still after restarting Gokapi. Yes, I'm certain the files I am trying to upload are not being used by anything else.

**Comment by Forceu** [comment]
Thanks, I was able to reproduce the problem and will have a look at it tomorrow.

**Comment by Forceu** [comment]
The issue should be fixed with e4e2bf0 - can you please try with the attached compiled version, if it is working now?
[gokapi.zip](https://github.com/Forceu/Gokapi/files/11073123/gokapi.zip)

**Comment by SilentSpartan** [comment]
It works great! Thanks for the fast replies and speedy fix.
