### ISSUE TITLE
Cleanup after interrupted uploads

### ISSUE THREAD

**Issue by PozoSer** [Forceu/Gokapi#96]
Hi,

Thanks for the amazing work. Really useful. 

I have found that if my upload gets interrupted, a file with equal size to the file that was being uploaded remains in the /data path. 

I assume that an entry is registered as well on the database.

Would it make sense to periodically cleanup the interrupted files so that no space is lost?

**Comment by Forceu** [comment]
What version are you using? And do the filenames of the remaining files start with "chunk" or "upload"? Because these files are deleted after 24 hours if an upload was not finished.
