### ISSUE TITLE
Feature Request: Share Via QR Code

### ISSUE THREAD

**Issue by arazilsongweaver** [Forceu/Gokapi#97]
This feature would add a "Share Via QR Code"  button to the "Actions" section of the administration page. Clicking the button would lead to another page featuring a QR Code for the file download page and an option to download the displayed QR Code image. The QR Code could then be scanned from the page or downloaded for distribution elsewhere.

Justification: This new feature would allow for easy file distribution to phones or other camera enabled devices.

**Comment by Forceu** [comment]
Added in 0eefdb1
